//
//  HypnososViewController.m
//  HypnoTimeOne
//
//  Created by Kevin Bowe on 6/27/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import "HypnosisViewController.h"


@implementation HypnosisViewController

- (id) init
{
    // Call the superclass's designed initializer...
    [super initWithNibName:nil bundle:nil];
    
    // Get the tab bar item...
    UITabBarItem *tbi = [self tabBarItem];
    
    // Give it a label...
    [tbi setTitle:@"Hypnosis"];
    
    /*
     Add Code to display the Hypnosis Icon 
     */
    
    // Create a UIImage from a file...
    UIImage *i = [UIImage imageNamed:@"Hypno.png"];
    
    // Put the image onthe tab bar item...
    [tbi setImage:i];
    
    return self;    
}


// This method gets called automatically when the view is created...
- (void) viewDidLoad
{
    [super viewDidLoad];
    
    // Set the background color of the view so we can see it...
    [[self view] setBackgroundColor:[UIColor orangeColor]];   
}


- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
{
    // Disregard parameters - nib name is an implementation detail...
    return [self init];

    /*  This code was generated by xCode...
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        // Custom initialization
    }
    return self;
    */  // xCode Generated...
}

- (void)dealloc
{
    [super dealloc];
}

- (void)didReceiveMemoryWarning
{
    // Releases the view if it doesn't have a superview.
    [super didReceiveMemoryWarning];
    
    // Release any cached data, images, etc that aren't in use.
}

#pragma mark - View lifecycle

/*
// Implement loadView to create a view hierarchy programmatically, without using a nib.
- (void)loadView
{
}
*/

/*
// Implement viewDidLoad to do additional setup after loading the view, typically from a nib.
- (void)viewDidLoad
{
    [super viewDidLoad];
}
*/

- (void)viewDidUnload
{
    [super viewDidUnload];
    // Release any retained subviews of the main view.
    // e.g. self.myOutlet = nil;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    // Return YES for supported orientations
    return (interfaceOrientation == UIInterfaceOrientationPortrait);
}

@end
